Exercise1
SiarheiKhmalEY/bootcamp pull request #1
Opened 2023-03-03 17:45 UTC by SiarheiKhmalEY

2023-03-09 10:22 UTC, jaroslawwoloch requested changes
remove idea project files and generated files

2023-03-09 10:22 UTC, jaroslawwoloch commented on src/Main.java
> +        try (BufferedWriter bufferedWriter = Files.newBufferedWriter(Path.of(OUTPUT))) {
write to sysout

2023-03-09 10:22 UTC, jaroslawwoloch commented on src/Main.java
> +                    throw new RuntimeException(e);
in real application don't throw Exception or RuntimeException this is a bad practice

2023-03-13 12:00 UTC, jaroslawwoloch approved these changes

2023-03-15 08:30 UTC, jaroslawwoloch requested changes
remove idea project file from repository

2023-03-15 10:36 UTC, SiarheiKhmalEY commented
> remove idea project file from repository

Already done. Thank You for the advice. I didn't check file .gitnore

2023-03-21 08:51 UTC, jaroslawwoloch approved these changes

2023-05-04 07:58 UTC, merged