Exercise3
SiarheiKhmalEY/bootcamp pull request #3
Opened 2023-03-03 17:49 UTC by SiarheiKhmalEY

2023-03-21 16:11 UTC, jaroslawwoloch requested changes
remove unnecessary files from repo

2023-03-21 16:11 UTC, jaroslawwoloch commented on src/Main.java
> +//        getAllClassesWithAnnotation(ScanMe.class, myObjectsToScan);
why commented?
remove commented code

2023-03-21 16:11 UTC, jaroslawwoloch commented on src/Main.java
> +        for (MyInterface element : elementList
formating - form method braces in same line but on for loop in next line - correct this

2023-03-21 16:11 UTC, jaroslawwoloch commented on src/Main.java
> +    public static void getAllClassesWithAnnotation(Class<? extends Annotation> classAnnotation, List<MyInterface> elementList) {
move to non static method

2023-03-30 15:41 UTC, SiarheiKhmalEY commented on src/Main.java
> +//        getAllClassesWithAnnotation(ScanMe.class, myObjectsToScan);
It's clarify which line run task. Anyway already deleted. Thank you

2023-03-30 15:41 UTC, SiarheiKhmalEY commented on src/Main.java
> +        for (MyInterface element : elementList
Sorry, my bad. Already done.

2023-03-30 15:42 UTC, SiarheiKhmalEY commented on src/Main.java
> +    public static void getAllClassesWithAnnotation(Class<? extends Annotation> classAnnotation, List<MyInterface> elementList) {
Done. Thank you.

2023-03-30 15:42 UTC, SiarheiKhmalEY commented
> 
Already deleted. Thank you

2023-04-03 13:02 UTC, jaroslawwoloch approved these changes

2023-05-04 08:13 UTC, merged